---
  plugins:
    - flowtype
    - jest
    - babel

  env:
    jest/globals: true
    node: true
    browser: true
    
  parser: babel-eslint

  extends:
    - 'airbnb-base'
    - 'plugin:jest/recommended'
    - 'plugin:flowtype/recommended'

  rules:
    no-console: 0
